### ISSUE TITLE
Cannot scrape hive-metastore 

### ISSUE THREAD

**Issue by duyquang8** [hyperqueryhq/whale#196]
Hi maintainers, 
I got this error using metastore on latest master branch
```Traceback (most recent call last):
  File "/home/duyquang6/.whale/bin/../libexec/build_script.py", line 23, in <module>
    pull()
  File "/home/duyquang6/.whale/libexec/env/lib/python3.8/site-packages/whale/__init__.py", line 175, in pull
    task.run()
  File "/home/duyquang6/.whale/libexec/env/lib/python3.8/site-packages/whale/task/__init__.py", line 30, in run
    self.loader.load(record)
  File "/home/duyquang6/.whale/libexec/env/lib/python3.8/site-packages/whale/loader/whale_loader.py", line 120, in load
    update_markdown(file_path, record)
  File "/home/duyquang6/.whale/libexec/env/lib/python3.8/site-packages/whale/loader/whale_loader.py", line 155, in update_markdown
    sections = section_method(sections, record)
  File "/home/duyquang6/.whale/libexec/env/lib/python3.8/site-packages/whale/loader/whale_loader.py", line 205, in _update_table_metadata
    table_metadata_blob = record.format_for_markdown()
AttributeError: 'TableMetadata' object has no attribute 'format_for_markdown'
thread 'main' panicked at 'Can't read file `/home/duyquang6/.whale/manifests/manifest.txt`', src/filesystem.rs:29:29```

**Comment by rsyi** [comment]
Thanks @duyquang8 !
